// Code generated by protoc-gen-go. DO NOT EDIT.
// source: FunctionRpc.proto

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import duration "github.com/golang/protobuf/ptypes/duration"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Indicates Failure/Success/Cancelled
type StatusResult_Status int32

const (
	StatusResult_Failure   StatusResult_Status = 0
	StatusResult_Success   StatusResult_Status = 1
	StatusResult_Cancelled StatusResult_Status = 2
)

var StatusResult_Status_name = map[int32]string{
	0: "Failure",
	1: "Success",
	2: "Cancelled",
}
var StatusResult_Status_value = map[string]int32{
	"Failure":   0,
	"Success":   1,
	"Cancelled": 2,
}

func (x StatusResult_Status) String() string {
	return proto.EnumName(StatusResult_Status_name, int32(x))
}
func (StatusResult_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_FunctionRpc_783c3044933d63dc, []int{4, 0}
}

// Types of File change operations (See link for more info: https://msdn.microsoft.com/en-us/library/t6xf43e0(v=vs.110).aspx)
type FileChangeEventRequest_Type int32

const (
	FileChangeEventRequest_Unknown FileChangeEventRequest_Type = 0
	FileChangeEventRequest_Created FileChangeEventRequest_Type = 1
	FileChangeEventRequest_Deleted FileChangeEventRequest_Type = 2
	FileChangeEventRequest_Changed FileChangeEventRequest_Type = 4
	FileChangeEventRequest_Renamed FileChangeEventRequest_Type = 8
	FileChangeEventRequest_All     FileChangeEventRequest_Type = 15
)

var FileChangeEventRequest_Type_name = map[int32]string{
	0:  "Unknown",
	1:  "Created",
	2:  "Deleted",
	4:  "Changed",
	8:  "Renamed",
	15: "All",
}
var FileChangeEventRequest_Type_value = map[string]int32{
	"Unknown": 0,
	"Created": 1,
	"Deleted": 2,
	"Changed": 4,
	"Renamed": 8,
	"All":     15,
}

func (x FileChangeEventRequest_Type) String() string {
	return proto.EnumName(FileChangeEventRequest_Type_name, int32(x))
}
func (FileChangeEventRequest_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_FunctionRpc_783c3044933d63dc, []int{7, 0}
}

// indicates whether a restart is needed, or reload succesfully
type WorkerActionResponse_Action int32

const (
	WorkerActionResponse_Restart WorkerActionResponse_Action = 0
	WorkerActionResponse_Reload  WorkerActionResponse_Action = 1
)

var WorkerActionResponse_Action_name = map[int32]string{
	0: "Restart",
	1: "Reload",
}
var WorkerActionResponse_Action_value = map[string]int32{
	"Restart": 0,
	"Reload":  1,
}

func (x WorkerActionResponse_Action) String() string {
	return proto.EnumName(WorkerActionResponse_Action_name, int32(x))
}
func (WorkerActionResponse_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_FunctionRpc_783c3044933d63dc, []int{8, 0}
}

// Indicates whether it is an input or output binding (or a fancy inout binding)
type BindingInfo_Direction int32

const (
	BindingInfo_in    BindingInfo_Direction = 0
	BindingInfo_out   BindingInfo_Direction = 1
	BindingInfo_inout BindingInfo_Direction = 2
)

var BindingInfo_Direction_name = map[int32]string{
	0: "in",
	1: "out",
	2: "inout",
}
var BindingInfo_Direction_value = map[string]int32{
	"in":    0,
	"out":   1,
	"inout": 2,
}

func (x BindingInfo_Direction) String() string {
	return proto.EnumName(BindingInfo_Direction_name, int32(x))
}
func (BindingInfo_Direction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_FunctionRpc_783c3044933d63dc, []int{19, 0}
}

// Matching ILogger semantics
// https://github.com/aspnet/Logging/blob/9506ccc3f3491488fe88010ef8b9eb64594abf95/src/Microsoft.Extensions.Logging/Logger.cs
// Level for the Log
type RpcLog_Level int32

const (
	RpcLog_Trace       RpcLog_Level = 0
	RpcLog_Debug       RpcLog_Level = 1
	RpcLog_Information RpcLog_Level = 2
	RpcLog_Warning     RpcLog_Level = 3
	RpcLog_Error       RpcLog_Level = 4
	RpcLog_Critical    RpcLog_Level = 5
	RpcLog_None        RpcLog_Level = 6
)

var RpcLog_Level_name = map[int32]string{
	0: "Trace",
	1: "Debug",
	2: "Information",
	3: "Warning",
	4: "Error",
	5: "Critical",
	6: "None",
}
var RpcLog_Level_value = map[string]int32{
	"Trace":       0,
	"Debug":       1,
	"Information": 2,
	"Warning":     3,
	"Error":       4,
	"Critical":    5,
	"None":        6,
}

func (x RpcLog_Level) String() string {
	return proto.EnumName(RpcLog_Level_name, int32(x))
}
func (RpcLog_Level) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_FunctionRpc_783c3044933d63dc, []int{20, 0}
}

type StreamingMessage struct {
	// Used to identify message between host and worker
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Payload of the message
	//
	// Types that are valid to be assigned to Content:
	//	*StreamingMessage_StartStream
	//	*StreamingMessage_WorkerInitRequest
	//	*StreamingMessage_WorkerInitResponse
	//	*StreamingMessage_WorkerHeartbeat
	//	*StreamingMessage_WorkerTerminate
	//	*StreamingMessage_WorkerStatusRequest
	//	*StreamingMessage_WorkerStatusResponse
	//	*StreamingMessage_FileChangeEventRequest
	//	*StreamingMessage_WorkerActionResponse
	//	*StreamingMessage_FunctionLoadRequest
	//	*StreamingMessage_FunctionLoadResponse
	//	*StreamingMessage_InvocationRequest
	//	*StreamingMessage_InvocationResponse
	//	*StreamingMessage_InvocationCancel
	//	*StreamingMessage_RpcLog
	Content              isStreamingMessage_Content `protobuf_oneof:"content"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *StreamingMessage) Reset()         { *m = StreamingMessage{} }
func (m *StreamingMessage) String() string { return proto.CompactTextString(m) }
func (*StreamingMessage) ProtoMessage()    {}
func (*StreamingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_FunctionRpc_783c3044933d63dc, []int{0}
}
func (m *StreamingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamingMessage.Unmarshal(m, b)
}
func (m *StreamingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamingMessage.Marshal(b, m, deterministic)
}
func (dst *StreamingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamingMessage.Merge(dst, src)
}
func (m *StreamingMessage) XXX_Size() int {
	return xxx_messageInfo_StreamingMessage.Size(m)
}
func (m *StreamingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StreamingMessage proto.InternalMessageInfo

type isStreamingMessage_Content interface {
	isStreamingMessage_Content()
}

type StreamingMessage_StartStream struct {
	StartStream *StartStream `protobuf:"bytes,20,opt,name=start_stream,json=startStream,proto3,oneof"`
}
type StreamingMessage_WorkerInitRequest struct {
	WorkerInitRequest *WorkerInitRequest `protobuf:"bytes,17,opt,name=worker_init_request,json=workerInitRequest,proto3,oneof"`
}
type StreamingMessage_WorkerInitResponse struct {
	WorkerInitResponse *WorkerInitResponse `protobuf:"bytes,16,opt,name=worker_init_response,json=workerInitResponse,proto3,oneof"`
}
type StreamingMessage_WorkerHeartbeat struct {
	WorkerHeartbeat *WorkerHeartbeat `protobuf:"bytes,15,opt,name=worker_heartbeat,json=workerHeartbeat,proto3,oneof"`
}
type StreamingMessage_WorkerTerminate struct {
	WorkerTerminate *WorkerTerminate `protobuf:"bytes,14,opt,name=worker_terminate,json=workerTerminate,proto3,oneof"`
}
type StreamingMessage_WorkerStatusRequest struct {
	WorkerStatusRequest *WorkerStatusRequest `protobuf:"bytes,12,opt,name=worker_status_request,json=workerStatusRequest,proto3,oneof"`
}
type StreamingMessage_WorkerStatusResponse struct {
	WorkerStatusResponse *WorkerStatusResponse `protobuf:"bytes,13,opt,name=worker_status_response,json=workerStatusResponse,proto3,oneof"`
}
type StreamingMessage_FileChangeEventRequest struct {
	FileChangeEventRequest *FileChangeEventRequest `protobuf:"bytes,6,opt,name=file_change_event_request,json=fileChangeEventRequest,proto3,oneof"`
}
type StreamingMessage_WorkerActionResponse struct {
	WorkerActionResponse *WorkerActionResponse `protobuf:"bytes,7,opt,name=worker_action_response,json=workerActionResponse,proto3,oneof"`
}
type StreamingMessage_FunctionLoadRequest struct {
	FunctionLoadRequest *FunctionLoadRequest `protobuf:"bytes,8,opt,name=function_load_request,json=functionLoadRequest,proto3,oneof"`
}
type StreamingMessage_FunctionLoadResponse struct {
	FunctionLoadResponse *FunctionLoadResponse `protobuf:"bytes,9,opt,name=function_load_response,json=functionLoadResponse,proto3,oneof"`
}
type StreamingMessage_InvocationRequest struct {
	InvocationRequest *InvocationRequest `protobuf:"bytes,4,opt,name=invocation_request,json=invocationRequest,proto3,oneof"`
}
type StreamingMessage_InvocationResponse struct {
	InvocationResponse *InvocationResponse `protobuf:"bytes,5,opt,name=invocation_response,json=invocationResponse,proto3,oneof"`
}
type StreamingMessage_InvocationCancel struct {
	InvocationCancel *InvocationCancel `protobuf:"bytes,21,opt,name=invocation_cancel,json=invocationCancel,proto3,oneof"`
}
type StreamingMessage_RpcLog struct {
	RpcLog *RpcLog `protobuf:"bytes,2,opt,name=rpc_log,json=rpcLog,proto3,oneof"`
}

func (*StreamingMessage_StartStream) isStreamingMessage_Content()            {}
func (*StreamingMessage_WorkerInitRequest) isStreamingMessage_Content()      {}
func (*StreamingMessage_WorkerInitResponse) isStreamingMessage_Content()     {}
func (*StreamingMessage_WorkerHeartbeat) isStreamingMessage_Content()        {}
func (*StreamingMessage_WorkerTerminate) isStreamingMessage_Content()        {}
func (*StreamingMessage_WorkerStatusRequest) isStreamingMessage_Content()    {}
func (*StreamingMessage_WorkerStatusResponse) isStreamingMessage_Content()   {}
func (*StreamingMessage_FileChangeEventRequest) isStreamingMessage_Content() {}
func (*StreamingMessage_WorkerActionResponse) isStreamingMessage_Content()   {}
func (*StreamingMessage_FunctionLoadRequest) isStreamingMessage_Content()    {}
func (*StreamingMessage_FunctionLoadResponse) isStreamingMessage_Content()   {}
func (*StreamingMessage_InvocationRequest) isStreamingMessage_Content()      {}
func (*StreamingMessage_InvocationResponse) isStreamingMessage_Content()     {}
func (*StreamingMessage_InvocationCancel) isStreamingMessage_Content()       {}
func (*StreamingMessage_RpcLog) isStreamingMessage_Content()                 {}

func (m *StreamingMessage) GetContent() isStreamingMessage_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *StreamingMessage) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *StreamingMessage) GetStartStream() *StartStream {
	if x, ok := m.GetContent().(*StreamingMessage_StartStream); ok {
		return x.StartStream
	}
	return nil
}

func (m *StreamingMessage) GetWorkerInitRequest() *WorkerInitRequest {
	if x, ok := m.GetContent().(*StreamingMessage_WorkerInitRequest); ok {
		return x.WorkerInitRequest
	}
	return nil
}

func (m *StreamingMessage) GetWorkerInitResponse() *WorkerInitResponse {
	if x, ok := m.GetContent().(*StreamingMessage_WorkerInitResponse); ok {
		return x.WorkerInitResponse
	}
	return nil
}

func (m *StreamingMessage) GetWorkerHeartbeat() *WorkerHeartbeat {
	if x, ok := m.GetContent().(*StreamingMessage_WorkerHeartbeat); ok {
		return x.WorkerHeartbeat
	}
	return nil
}

func (m *StreamingMessage) GetWorkerTerminate() *WorkerTerminate {
	if x, ok := m.GetContent().(*StreamingMessage_WorkerTerminate); ok {
		return x.WorkerTerminate
	}
	return nil
}

func (m *StreamingMessage) GetWorkerStatusRequest() *WorkerStatusRequest {
	if x, ok := m.GetContent().(*StreamingMessage_WorkerStatusRequest); ok {
		return x.WorkerStatusRequest
	}
	return nil
}

func (m *StreamingMessage) GetWorkerStatusResponse() *WorkerStatusResponse {
	if x, ok := m.GetContent().(*StreamingMessage_WorkerStatusResponse); ok {
		return x.WorkerStatusResponse
	}
	return nil
}

func (m *StreamingMessage) GetFileChangeEventRequest() *FileChangeEventRequest {
	if x, ok := m.GetContent().(*StreamingMessage_FileChangeEventRequest); ok {
		return x.FileChangeEventRequest
	}
	return nil
}

func (m *StreamingMessage) GetWorkerActionResponse() *WorkerActionResponse {
	if x, ok := m.GetContent().(*StreamingMessage_WorkerActionResponse); ok {
		return x.WorkerActionResponse
	}
	return nil
}

func (m *StreamingMessage) GetFunctionLoadRequest() *FunctionLoadRequest {
	if x, ok := m.GetContent().(*StreamingMessage_FunctionLoadRequest); ok {
		return x.FunctionLoadRequest
	}
	return nil
}

func (m *StreamingMessage) GetFunctionLoadResponse() *FunctionLoadResponse {
	if x, ok := m.GetContent().(*StreamingMessage_FunctionLoadResponse); ok {
		return x.FunctionLoadResponse
	}
	return nil
}

func (m *StreamingMessage) GetInvocationRequest() *InvocationRequest {
	if x, ok := m.GetContent().(*StreamingMessage_InvocationRequest); ok {
		return x.InvocationRequest
	}
	return nil
}

func (m *StreamingMessage) GetInvocationResponse() *InvocationResponse {
	if x, ok := m.GetContent().(*StreamingMessage_InvocationResponse); ok {
		return x.InvocationResponse
	}
	return nil
}

func (m *StreamingMessage) GetInvocationCancel() *InvocationCancel {
	if x, ok := m.GetContent().(*StreamingMessage_InvocationCancel); ok {
		return x.InvocationCancel
	}
	return nil
}

func (m *StreamingMessage) GetRpcLog() *RpcLog {
	if x, ok := m.GetContent().(*StreamingMessage_RpcLog); ok {
		return x.RpcLog
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*StreamingMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _StreamingMessage_OneofMarshaler, _StreamingMessage_OneofUnmarshaler, _StreamingMessage_OneofSizer, []interface{}{
		(*StreamingMessage_StartStream)(nil),
		(*StreamingMessage_WorkerInitRequest)(nil),
		(*StreamingMessage_WorkerInitResponse)(nil),
		(*StreamingMessage_WorkerHeartbeat)(nil),
		(*StreamingMessage_WorkerTerminate)(nil),
		(*StreamingMessage_WorkerStatusRequest)(nil),
		(*StreamingMessage_WorkerStatusResponse)(nil),
		(*StreamingMessage_FileChangeEventRequest)(nil),
		(*StreamingMessage_WorkerActionResponse)(nil),
		(*StreamingMessage_FunctionLoadRequest)(nil),
		(*StreamingMessage_FunctionLoadResponse)(nil),
		(*StreamingMessage_InvocationRequest)(nil),
		(*StreamingMessage_InvocationResponse)(nil),
		(*StreamingMessage_InvocationCancel)(nil),
		(*StreamingMessage_RpcLog)(nil),
	}
}

func _StreamingMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*StreamingMessage)
	// content
	switch x := m.Content.(type) {
	case *StreamingMessage_StartStream:
		b.EncodeVarint(20<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.StartStream); err != nil {
			return err
		}
	case *StreamingMessage_WorkerInitRequest:
		b.EncodeVarint(17<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.WorkerInitRequest); err != nil {
			return err
		}
	case *StreamingMessage_WorkerInitResponse:
		b.EncodeVarint(16<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.WorkerInitResponse); err != nil {
			return err
		}
	case *StreamingMessage_WorkerHeartbeat:
		b.EncodeVarint(15<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.WorkerHeartbeat); err != nil {
			return err
		}
	case *StreamingMessage_WorkerTerminate:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.WorkerTerminate); err != nil {
			return err
		}
	case *StreamingMessage_WorkerStatusRequest:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.WorkerStatusRequest); err != nil {
			return err
		}
	case *StreamingMessage_WorkerStatusResponse:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.WorkerStatusResponse); err != nil {
			return err
		}
	case *StreamingMessage_FileChangeEventRequest:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FileChangeEventRequest); err != nil {
			return err
		}
	case *StreamingMessage_WorkerActionResponse:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.WorkerActionResponse); err != nil {
			return err
		}
	case *StreamingMessage_FunctionLoadRequest:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FunctionLoadRequest); err != nil {
			return err
		}
	case *StreamingMessage_FunctionLoadResponse:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FunctionLoadResponse); err != nil {
			return err
		}
	case *StreamingMessage_InvocationRequest:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.InvocationRequest); err != nil {
			return err
		}
	case *StreamingMessage_InvocationResponse:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.InvocationResponse); err != nil {
			return err
		}
	case *StreamingMessage_InvocationCancel:
		b.EncodeVarint(21<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.InvocationCancel); err != nil {
			return err
		}
	case *StreamingMessage_RpcLog:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RpcLog); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("StreamingMessage.Content has unexpected type %T", x)
	}
	return nil
}

func _StreamingMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*StreamingMessage)
	switch tag {
	case 20: // content.start_stream
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StartStream)
		err := b.DecodeMessage(msg)
		m.Content = &StreamingMessage_StartStream{msg}
		return true, err
	case 17: // content.worker_init_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(WorkerInitRequest)
		err := b.DecodeMessage(msg)
		m.Content = &StreamingMessage_WorkerInitRequest{msg}
		return true, err
	case 16: // content.worker_init_response
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(WorkerInitResponse)
		err := b.DecodeMessage(msg)
		m.Content = &StreamingMessage_WorkerInitResponse{msg}
		return true, err
	case 15: // content.worker_heartbeat
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(WorkerHeartbeat)
		err := b.DecodeMessage(msg)
		m.Content = &StreamingMessage_WorkerHeartbeat{msg}
		return true, err
	case 14: // content.worker_terminate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(WorkerTerminate)
		err := b.DecodeMessage(msg)
		m.Content = &StreamingMessage_WorkerTerminate{msg}
		return true, err
	case 12: // content.worker_status_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(WorkerStatusRequest)
		err := b.DecodeMessage(msg)
		m.Content = &StreamingMessage_WorkerStatusRequest{msg}
		return true, err
	case 13: // content.worker_status_response
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(WorkerStatusResponse)
		err := b.DecodeMessage(msg)
		m.Content = &StreamingMessage_WorkerStatusResponse{msg}
		return true, err
	case 6: // content.file_change_event_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FileChangeEventRequest)
		err := b.DecodeMessage(msg)
		m.Content = &StreamingMessage_FileChangeEventRequest{msg}
		return true, err
	case 7: // content.worker_action_response
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(WorkerActionResponse)
		err := b.DecodeMessage(msg)
		m.Content = &StreamingMessage_WorkerActionResponse{msg}
		return true, err
	case 8: // content.function_load_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FunctionLoadRequest)
		err := b.DecodeMessage(msg)
		m.Content = &StreamingMessage_FunctionLoadRequest{msg}
		return true, err
	case 9: // content.function_load_response
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FunctionLoadResponse)
		err := b.DecodeMessage(msg)
		m.Content = &StreamingMessage_FunctionLoadResponse{msg}
		return true, err
	case 4: // content.invocation_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(InvocationRequest)
		err := b.DecodeMessage(msg)
		m.Content = &StreamingMessage_InvocationRequest{msg}
		return true, err
	case 5: // content.invocation_response
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(InvocationResponse)
		err := b.DecodeMessage(msg)
		m.Content = &StreamingMessage_InvocationResponse{msg}
		return true, err
	case 21: // content.invocation_cancel
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(InvocationCancel)
		err := b.DecodeMessage(msg)
		m.Content = &StreamingMessage_InvocationCancel{msg}
		return true, err
	case 2: // content.rpc_log
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RpcLog)
		err := b.DecodeMessage(msg)
		m.Content = &StreamingMessage_RpcLog{msg}
		return true, err
	default:
		return false, nil
	}
}

func _StreamingMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*StreamingMessage)
	// content
	switch x := m.Content.(type) {
	case *StreamingMessage_StartStream:
		s := proto.Size(x.StartStream)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StreamingMessage_WorkerInitRequest:
		s := proto.Size(x.WorkerInitRequest)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StreamingMessage_WorkerInitResponse:
		s := proto.Size(x.WorkerInitResponse)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StreamingMessage_WorkerHeartbeat:
		s := proto.Size(x.WorkerHeartbeat)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StreamingMessage_WorkerTerminate:
		s := proto.Size(x.WorkerTerminate)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StreamingMessage_WorkerStatusRequest:
		s := proto.Size(x.WorkerStatusRequest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StreamingMessage_WorkerStatusResponse:
		s := proto.Size(x.WorkerStatusResponse)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StreamingMessage_FileChangeEventRequest:
		s := proto.Size(x.FileChangeEventRequest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StreamingMessage_WorkerActionResponse:
		s := proto.Size(x.WorkerActionResponse)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StreamingMessage_FunctionLoadRequest:
		s := proto.Size(x.FunctionLoadRequest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StreamingMessage_FunctionLoadResponse:
		s := proto.Size(x.FunctionLoadResponse)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StreamingMessage_InvocationRequest:
		s := proto.Size(x.InvocationRequest)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StreamingMessage_InvocationResponse:
		s := proto.Size(x.InvocationResponse)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StreamingMessage_InvocationCancel:
		s := proto.Size(x.InvocationCancel)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StreamingMessage_RpcLog:
		s := proto.Size(x.RpcLog)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Worker sends the host information identifying itself
type StartStream struct {
	// id of the worker
	WorkerId             string   `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartStream) Reset()         { *m = StartStream{} }
func (m *StartStream) String() string { return proto.CompactTextString(m) }
func (*StartStream) ProtoMessage()    {}
func (*StartStream) Descriptor() ([]byte, []int) {
	return fileDescriptor_FunctionRpc_783c3044933d63dc, []int{1}
}
func (m *StartStream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartStream.Unmarshal(m, b)
}
func (m *StartStream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartStream.Marshal(b, m, deterministic)
}
func (dst *StartStream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartStream.Merge(dst, src)
}
func (m *StartStream) XXX_Size() int {
	return xxx_messageInfo_StartStream.Size(m)
}
func (m *StartStream) XXX_DiscardUnknown() {
	xxx_messageInfo_StartStream.DiscardUnknown(m)
}

var xxx_messageInfo_StartStream proto.InternalMessageInfo

func (m *StartStream) GetWorkerId() string {
	if m != nil {
		return m.WorkerId
	}
	return ""
}

// Host requests the worker to initialize itself
type WorkerInitRequest struct {
	// version of the host sending init request
	HostVersion string `protobuf:"bytes,1,opt,name=host_version,json=hostVersion,proto3" json:"host_version,omitempty"`
	// A map of host supported features/capabilities
	Capabilities map[string]string `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// inform worker of supported categories and their levels
	// i.e. Worker = Verbose, Function.MyFunc = None
	LogCategories        map[string]RpcLog_Level `protobuf:"bytes,3,rep,name=log_categories,json=logCategories,proto3" json:"log_categories,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=AzureFunctionsRpcMessages.RpcLog_Level"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *WorkerInitRequest) Reset()         { *m = WorkerInitRequest{} }
func (m *WorkerInitRequest) String() string { return proto.CompactTextString(m) }
func (*WorkerInitRequest) ProtoMessage()    {}
func (*WorkerInitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_FunctionRpc_783c3044933d63dc, []int{2}
}
func (m *WorkerInitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkerInitRequest.Unmarshal(m, b)
}
func (m *WorkerInitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkerInitRequest.Marshal(b, m, deterministic)
}
func (dst *WorkerInitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkerInitRequest.Merge(dst, src)
}
func (m *WorkerInitRequest) XXX_Size() int {
	return xxx_messageInfo_WorkerInitRequest.Size(m)
}
func (m *WorkerInitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkerInitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WorkerInitRequest proto.InternalMessageInfo

func (m *WorkerInitRequest) GetHostVersion() string {
	if m != nil {
		return m.HostVersion
	}
	return ""
}

func (m *WorkerInitRequest) GetCapabilities() map[string]string {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

func (m *WorkerInitRequest) GetLogCategories() map[string]RpcLog_Level {
	if m != nil {
		return m.LogCategories
	}
	return nil
}

// Worker responds with the result of initializing itself
type WorkerInitResponse struct {
	// Version of worker
	WorkerVersion string `protobuf:"bytes,1,opt,name=worker_version,json=workerVersion,proto3" json:"worker_version,omitempty"`
	// A map of worker supported features/capabilities
	Capabilities map[string]string `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Status of the response
	Result               *StatusResult `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *WorkerInitResponse) Reset()         { *m = WorkerInitResponse{} }
func (m *WorkerInitResponse) String() string { return proto.CompactTextString(m) }
func (*WorkerInitResponse) ProtoMessage()    {}
func (*WorkerInitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_FunctionRpc_783c3044933d63dc, []int{3}
}
func (m *WorkerInitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkerInitResponse.Unmarshal(m, b)
}
func (m *WorkerInitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkerInitResponse.Marshal(b, m, deterministic)
}
func (dst *WorkerInitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkerInitResponse.Merge(dst, src)
}
func (m *WorkerInitResponse) XXX_Size() int {
	return xxx_messageInfo_WorkerInitResponse.Size(m)
}
func (m *WorkerInitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkerInitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WorkerInitResponse proto.InternalMessageInfo

func (m *WorkerInitResponse) GetWorkerVersion() string {
	if m != nil {
		return m.WorkerVersion
	}
	return ""
}

func (m *WorkerInitResponse) GetCapabilities() map[string]string {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

func (m *WorkerInitResponse) GetResult() *StatusResult {
	if m != nil {
		return m.Result
	}
	return nil
}

// Used by the host to determine success/failure/cancellation
type StatusResult struct {
	// Status for the given result
	Status StatusResult_Status `protobuf:"varint,4,opt,name=status,proto3,enum=AzureFunctionsRpcMessages.StatusResult_Status" json:"status,omitempty"`
	// Specific message about the result
	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// Exception message (if exists) for the status
	Exception *RpcException `protobuf:"bytes,2,opt,name=exception,proto3" json:"exception,omitempty"`
	// Captured logs or relevant details can use the logs property
	Logs                 []*RpcLog `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *StatusResult) Reset()         { *m = StatusResult{} }
func (m *StatusResult) String() string { return proto.CompactTextString(m) }
func (*StatusResult) ProtoMessage()    {}
func (*StatusResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_FunctionRpc_783c3044933d63dc, []int{4}
}
func (m *StatusResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResult.Unmarshal(m, b)
}
func (m *StatusResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResult.Marshal(b, m, deterministic)
}
func (dst *StatusResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResult.Merge(dst, src)
}
func (m *StatusResult) XXX_Size() int {
	return xxx_messageInfo_StatusResult.Size(m)
}
func (m *StatusResult) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResult.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResult proto.InternalMessageInfo

func (m *StatusResult) GetStatus() StatusResult_Status {
	if m != nil {
		return m.Status
	}
	return StatusResult_Failure
}

func (m *StatusResult) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *StatusResult) GetException() *RpcException {
	if m != nil {
		return m.Exception
	}
	return nil
}

func (m *StatusResult) GetLogs() []*RpcLog {
	if m != nil {
		return m.Logs
	}
	return nil
}

// Message is empty by design - Will add more fields in future if needed
type WorkerHeartbeat struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkerHeartbeat) Reset()         { *m = WorkerHeartbeat{} }
func (m *WorkerHeartbeat) String() string { return proto.CompactTextString(m) }
func (*WorkerHeartbeat) ProtoMessage()    {}
func (*WorkerHeartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_FunctionRpc_783c3044933d63dc, []int{5}
}
func (m *WorkerHeartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkerHeartbeat.Unmarshal(m, b)
}
func (m *WorkerHeartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkerHeartbeat.Marshal(b, m, deterministic)
}
func (dst *WorkerHeartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkerHeartbeat.Merge(dst, src)
}
func (m *WorkerHeartbeat) XXX_Size() int {
	return xxx_messageInfo_WorkerHeartbeat.Size(m)
}
func (m *WorkerHeartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkerHeartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_WorkerHeartbeat proto.InternalMessageInfo

// Warning before killing the process after grace_period
// Worker self terminates ..no response on this
type WorkerTerminate struct {
	GracePeriod          *duration.Duration `protobuf:"bytes,1,opt,name=grace_period,json=gracePeriod,proto3" json:"grace_period,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *WorkerTerminate) Reset()         { *m = WorkerTerminate{} }
func (m *WorkerTerminate) String() string { return proto.CompactTextString(m) }
func (*WorkerTerminate) ProtoMessage()    {}
func (*WorkerTerminate) Descriptor() ([]byte, []int) {
	return fileDescriptor_FunctionRpc_783c3044933d63dc, []int{6}
}
func (m *WorkerTerminate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkerTerminate.Unmarshal(m, b)
}
func (m *WorkerTerminate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkerTerminate.Marshal(b, m, deterministic)
}
func (dst *WorkerTerminate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkerTerminate.Merge(dst, src)
}
func (m *WorkerTerminate) XXX_Size() int {
	return xxx_messageInfo_WorkerTerminate.Size(m)
}
func (m *WorkerTerminate) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkerTerminate.DiscardUnknown(m)
}

var xxx_messageInfo_WorkerTerminate proto.InternalMessageInfo

func (m *WorkerTerminate) GetGracePeriod() *duration.Duration {
	if m != nil {
		return m.GracePeriod
	}
	return nil
}

// Host notifies worker of file content change
type FileChangeEventRequest struct {
	// type for this event
	Type FileChangeEventRequest_Type `protobuf:"varint,1,opt,name=type,proto3,enum=AzureFunctionsRpcMessages.FileChangeEventRequest_Type" json:"type,omitempty"`
	// full file path for the file change notification
	FullPath string `protobuf:"bytes,2,opt,name=full_path,json=fullPath,proto3" json:"full_path,omitempty"`
	// Name of the function affected
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileChangeEventRequest) Reset()         { *m = FileChangeEventRequest{} }
func (m *FileChangeEventRequest) String() string { return proto.CompactTextString(m) }
func (*FileChangeEventRequest) ProtoMessage()    {}
func (*FileChangeEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_FunctionRpc_783c3044933d63dc, []int{7}
}
func (m *FileChangeEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileChangeEventRequest.Unmarshal(m, b)
}
func (m *FileChangeEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileChangeEventRequest.Marshal(b, m, deterministic)
}
func (dst *FileChangeEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileChangeEventRequest.Merge(dst, src)
}
func (m *FileChangeEventRequest) XXX_Size() int {
	return xxx_messageInfo_FileChangeEventRequest.Size(m)
}
func (m *FileChangeEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileChangeEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileChangeEventRequest proto.InternalMessageInfo

func (m *FileChangeEventRequest) GetType() FileChangeEventRequest_Type {
	if m != nil {
		return m.Type
	}
	return FileChangeEventRequest_Unknown
}

func (m *FileChangeEventRequest) GetFullPath() string {
	if m != nil {
		return m.FullPath
	}
	return ""
}

func (m *FileChangeEventRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Indicates whether worker reloaded successfully or needs a restart
type WorkerActionResponse struct {
	// action for this response
	Action WorkerActionResponse_Action `protobuf:"varint,1,opt,name=action,proto3,enum=AzureFunctionsRpcMessages.WorkerActionResponse_Action" json:"action,omitempty"`
	// text reason for the response
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkerActionResponse) Reset()         { *m = WorkerActionResponse{} }
func (m *WorkerActionResponse) String() string { return proto.CompactTextString(m) }
func (*WorkerActionResponse) ProtoMessage()    {}
func (*WorkerActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_FunctionRpc_783c3044933d63dc, []int{8}
}
func (m *WorkerActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkerActionResponse.Unmarshal(m, b)
}
func (m *WorkerActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkerActionResponse.Marshal(b, m, deterministic)
}
func (dst *WorkerActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkerActionResponse.Merge(dst, src)
}
func (m *WorkerActionResponse) XXX_Size() int {
	return xxx_messageInfo_WorkerActionResponse.Size(m)
}
func (m *WorkerActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkerActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WorkerActionResponse proto.InternalMessageInfo

func (m *WorkerActionResponse) GetAction() WorkerActionResponse_Action {
	if m != nil {
		return m.Action
	}
	return WorkerActionResponse_Restart
}

func (m *WorkerActionResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

// NOT USED
type WorkerStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkerStatusRequest) Reset()         { *m = WorkerStatusRequest{} }
func (m *WorkerStatusRequest) String() string { return proto.CompactTextString(m) }
func (*WorkerStatusRequest) ProtoMessage()    {}
func (*WorkerStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_FunctionRpc_783c3044933d63dc, []int{9}
}
func (m *WorkerStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkerStatusRequest.Unmarshal(m, b)
}
func (m *WorkerStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkerStatusRequest.Marshal(b, m, deterministic)
}
func (dst *WorkerStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkerStatusRequest.Merge(dst, src)
}
func (m *WorkerStatusRequest) XXX_Size() int {
	return xxx_messageInfo_WorkerStatusRequest.Size(m)
}
func (m *WorkerStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkerStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WorkerStatusRequest proto.InternalMessageInfo

// NOT USED
type WorkerStatusResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkerStatusResponse) Reset()         { *m = WorkerStatusResponse{} }
func (m *WorkerStatusResponse) String() string { return proto.CompactTextString(m) }
func (*WorkerStatusResponse) ProtoMessage()    {}
func (*WorkerStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_FunctionRpc_783c3044933d63dc, []int{10}
}
func (m *WorkerStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkerStatusResponse.Unmarshal(m, b)
}
func (m *WorkerStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkerStatusResponse.Marshal(b, m, deterministic)
}
func (dst *WorkerStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkerStatusResponse.Merge(dst, src)
}
func (m *WorkerStatusResponse) XXX_Size() int {
	return xxx_messageInfo_WorkerStatusResponse.Size(m)
}
func (m *WorkerStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkerStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WorkerStatusResponse proto.InternalMessageInfo

// Host tells the worker to load a Function
type FunctionLoadRequest struct {
	// unique function identifier (avoid name collisions, facilitate reload case)
	FunctionId string `protobuf:"bytes,1,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	// Metadata for the request
	Metadata             *RpcFunctionMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FunctionLoadRequest) Reset()         { *m = FunctionLoadRequest{} }
func (m *FunctionLoadRequest) String() string { return proto.CompactTextString(m) }
func (*FunctionLoadRequest) ProtoMessage()    {}
func (*FunctionLoadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_FunctionRpc_783c3044933d63dc, []int{11}
}
func (m *FunctionLoadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionLoadRequest.Unmarshal(m, b)
}
func (m *FunctionLoadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionLoadRequest.Marshal(b, m, deterministic)
}
func (dst *FunctionLoadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionLoadRequest.Merge(dst, src)
}
func (m *FunctionLoadRequest) XXX_Size() int {
	return xxx_messageInfo_FunctionLoadRequest.Size(m)
}
func (m *FunctionLoadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionLoadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionLoadRequest proto.InternalMessageInfo

func (m *FunctionLoadRequest) GetFunctionId() string {
	if m != nil {
		return m.FunctionId
	}
	return ""
}

func (m *FunctionLoadRequest) GetMetadata() *RpcFunctionMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// Worker tells host result of reload
type FunctionLoadResponse struct {
	// unique function identifier
	FunctionId string `protobuf:"bytes,1,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	// Result of load operation
	Result               *StatusResult `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FunctionLoadResponse) Reset()         { *m = FunctionLoadResponse{} }
func (m *FunctionLoadResponse) String() string { return proto.CompactTextString(m) }
func (*FunctionLoadResponse) ProtoMessage()    {}
func (*FunctionLoadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_FunctionRpc_783c3044933d63dc, []int{12}
}
func (m *FunctionLoadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionLoadResponse.Unmarshal(m, b)
}
func (m *FunctionLoadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionLoadResponse.Marshal(b, m, deterministic)
}
func (dst *FunctionLoadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionLoadResponse.Merge(dst, src)
}
func (m *FunctionLoadResponse) XXX_Size() int {
	return xxx_messageInfo_FunctionLoadResponse.Size(m)
}
func (m *FunctionLoadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionLoadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionLoadResponse proto.InternalMessageInfo

func (m *FunctionLoadResponse) GetFunctionId() string {
	if m != nil {
		return m.FunctionId
	}
	return ""
}

func (m *FunctionLoadResponse) GetResult() *StatusResult {
	if m != nil {
		return m.Result
	}
	return nil
}

// Information on how a Function should be loaded and its bindings
type RpcFunctionMetadata struct {
	// TODO: do we want the host's name - the language worker might do a better job of assignment than the host
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// base directory for the Function
	Directory string `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	// Script file specified
	ScriptFile string `protobuf:"bytes,2,opt,name=script_file,json=scriptFile,proto3" json:"script_file,omitempty"`
	// Entry point specified
	EntryPoint string `protobuf:"bytes,3,opt,name=entry_point,json=entryPoint,proto3" json:"entry_point,omitempty"`
	// Bindings info
	Bindings             map[string]*BindingInfo `protobuf:"bytes,6,rep,name=bindings,proto3" json:"bindings,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *RpcFunctionMetadata) Reset()         { *m = RpcFunctionMetadata{} }
func (m *RpcFunctionMetadata) String() string { return proto.CompactTextString(m) }
func (*RpcFunctionMetadata) ProtoMessage()    {}
func (*RpcFunctionMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_FunctionRpc_783c3044933d63dc, []int{13}
}
func (m *RpcFunctionMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcFunctionMetadata.Unmarshal(m, b)
}
func (m *RpcFunctionMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcFunctionMetadata.Marshal(b, m, deterministic)
}
func (dst *RpcFunctionMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcFunctionMetadata.Merge(dst, src)
}
func (m *RpcFunctionMetadata) XXX_Size() int {
	return xxx_messageInfo_RpcFunctionMetadata.Size(m)
}
func (m *RpcFunctionMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcFunctionMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_RpcFunctionMetadata proto.InternalMessageInfo

func (m *RpcFunctionMetadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RpcFunctionMetadata) GetDirectory() string {
	if m != nil {
		return m.Directory
	}
	return ""
}

func (m *RpcFunctionMetadata) GetScriptFile() string {
	if m != nil {
		return m.ScriptFile
	}
	return ""
}

func (m *RpcFunctionMetadata) GetEntryPoint() string {
	if m != nil {
		return m.EntryPoint
	}
	return ""
}

func (m *RpcFunctionMetadata) GetBindings() map[string]*BindingInfo {
	if m != nil {
		return m.Bindings
	}
	return nil
}

// Host requests worker to invoke a Function
type InvocationRequest struct {
	// Unique id for each invocation
	InvocationId string `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	// Unique id for each Function
	FunctionId string `protobuf:"bytes,2,opt,name=function_id,json=functionId,proto3" json:"function_id,omitempty"`
	// Input bindings (include trigger)
	InputData []*ParameterBinding `protobuf:"bytes,3,rep,name=input_data,json=inputData,proto3" json:"input_data,omitempty"`
	// binding metadata from trigger
	TriggerMetadata      map[string]*TypedData `protobuf:"bytes,4,rep,name=trigger_metadata,json=triggerMetadata,proto3" json:"trigger_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *InvocationRequest) Reset()         { *m = InvocationRequest{} }
func (m *InvocationRequest) String() string { return proto.CompactTextString(m) }
func (*InvocationRequest) ProtoMessage()    {}
func (*InvocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_FunctionRpc_783c3044933d63dc, []int{14}
}
func (m *InvocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvocationRequest.Unmarshal(m, b)
}
func (m *InvocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvocationRequest.Marshal(b, m, deterministic)
}
func (dst *InvocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvocationRequest.Merge(dst, src)
}
func (m *InvocationRequest) XXX_Size() int {
	return xxx_messageInfo_InvocationRequest.Size(m)
}
func (m *InvocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvocationRequest proto.InternalMessageInfo

func (m *InvocationRequest) GetInvocationId() string {
	if m != nil {
		return m.InvocationId
	}
	return ""
}

func (m *InvocationRequest) GetFunctionId() string {
	if m != nil {
		return m.FunctionId
	}
	return ""
}

func (m *InvocationRequest) GetInputData() []*ParameterBinding {
	if m != nil {
		return m.InputData
	}
	return nil
}

func (m *InvocationRequest) GetTriggerMetadata() map[string]*TypedData {
	if m != nil {
		return m.TriggerMetadata
	}
	return nil
}

// Host requests worker to cancel invocation
type InvocationCancel struct {
	// Unique id for invocation
	InvocationId string `protobuf:"bytes,2,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	// Time period before force shutdown
	GracePeriod          *duration.Duration `protobuf:"bytes,1,opt,name=grace_period,json=gracePeriod,proto3" json:"grace_period,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *InvocationCancel) Reset()         { *m = InvocationCancel{} }
func (m *InvocationCancel) String() string { return proto.CompactTextString(m) }
func (*InvocationCancel) ProtoMessage()    {}
func (*InvocationCancel) Descriptor() ([]byte, []int) {
	return fileDescriptor_FunctionRpc_783c3044933d63dc, []int{15}
}
func (m *InvocationCancel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvocationCancel.Unmarshal(m, b)
}
func (m *InvocationCancel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvocationCancel.Marshal(b, m, deterministic)
}
func (dst *InvocationCancel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvocationCancel.Merge(dst, src)
}
func (m *InvocationCancel) XXX_Size() int {
	return xxx_messageInfo_InvocationCancel.Size(m)
}
func (m *InvocationCancel) XXX_DiscardUnknown() {
	xxx_messageInfo_InvocationCancel.DiscardUnknown(m)
}

var xxx_messageInfo_InvocationCancel proto.InternalMessageInfo

func (m *InvocationCancel) GetInvocationId() string {
	if m != nil {
		return m.InvocationId
	}
	return ""
}

func (m *InvocationCancel) GetGracePeriod() *duration.Duration {
	if m != nil {
		return m.GracePeriod
	}
	return nil
}

// Worker responds with status of Invocation
type InvocationResponse struct {
	// Unique id for invocation
	InvocationId string `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	// Output binding data
	OutputData []*ParameterBinding `protobuf:"bytes,2,rep,name=output_data,json=outputData,proto3" json:"output_data,omitempty"`
	// data returned from Function (for $return and triggers with return support)
	ReturnValue *TypedData `protobuf:"bytes,4,opt,name=return_value,json=returnValue,proto3" json:"return_value,omitempty"`
	// Status of the invocation (success/failure/canceled)
	Result               *StatusResult `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *InvocationResponse) Reset()         { *m = InvocationResponse{} }
func (m *InvocationResponse) String() string { return proto.CompactTextString(m) }
func (*InvocationResponse) ProtoMessage()    {}
func (*InvocationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_FunctionRpc_783c3044933d63dc, []int{16}
}
func (m *InvocationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvocationResponse.Unmarshal(m, b)
}
func (m *InvocationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvocationResponse.Marshal(b, m, deterministic)
}
func (dst *InvocationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvocationResponse.Merge(dst, src)
}
func (m *InvocationResponse) XXX_Size() int {
	return xxx_messageInfo_InvocationResponse.Size(m)
}
func (m *InvocationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InvocationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InvocationResponse proto.InternalMessageInfo

func (m *InvocationResponse) GetInvocationId() string {
	if m != nil {
		return m.InvocationId
	}
	return ""
}

func (m *InvocationResponse) GetOutputData() []*ParameterBinding {
	if m != nil {
		return m.OutputData
	}
	return nil
}

func (m *InvocationResponse) GetReturnValue() *TypedData {
	if m != nil {
		return m.ReturnValue
	}
	return nil
}

func (m *InvocationResponse) GetResult() *StatusResult {
	if m != nil {
		return m.Result
	}
	return nil
}

// Used to encapsulate data which could be a variety of types
type TypedData struct {
	// Types that are valid to be assigned to Data:
	//	*TypedData_String_
	//	*TypedData_Json
	//	*TypedData_Bytes
	//	*TypedData_Stream
	//	*TypedData_Http
	//	*TypedData_Int
	//	*TypedData_Double
	Data                 isTypedData_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TypedData) Reset()         { *m = TypedData{} }
func (m *TypedData) String() string { return proto.CompactTextString(m) }
func (*TypedData) ProtoMessage()    {}
func (*TypedData) Descriptor() ([]byte, []int) {
	return fileDescriptor_FunctionRpc_783c3044933d63dc, []int{17}
}
func (m *TypedData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypedData.Unmarshal(m, b)
}
func (m *TypedData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypedData.Marshal(b, m, deterministic)
}
func (dst *TypedData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypedData.Merge(dst, src)
}
func (m *TypedData) XXX_Size() int {
	return xxx_messageInfo_TypedData.Size(m)
}
func (m *TypedData) XXX_DiscardUnknown() {
	xxx_messageInfo_TypedData.DiscardUnknown(m)
}

var xxx_messageInfo_TypedData proto.InternalMessageInfo

type isTypedData_Data interface {
	isTypedData_Data()
}

type TypedData_String_ struct {
	String_ string `protobuf:"bytes,1,opt,name=string,proto3,oneof"`
}
type TypedData_Json struct {
	Json string `protobuf:"bytes,2,opt,name=json,proto3,oneof"`
}
type TypedData_Bytes struct {
	Bytes []byte `protobuf:"bytes,3,opt,name=bytes,proto3,oneof"`
}
type TypedData_Stream struct {
	Stream []byte `protobuf:"bytes,4,opt,name=stream,proto3,oneof"`
}
type TypedData_Http struct {
	Http *RpcHttp `protobuf:"bytes,5,opt,name=http,proto3,oneof"`
}
type TypedData_Int struct {
	Int int64 `protobuf:"zigzag64,6,opt,name=int,proto3,oneof"`
}
type TypedData_Double struct {
	Double float64 `protobuf:"fixed64,7,opt,name=double,proto3,oneof"`
}

func (*TypedData_String_) isTypedData_Data() {}
func (*TypedData_Json) isTypedData_Data()    {}
func (*TypedData_Bytes) isTypedData_Data()   {}
func (*TypedData_Stream) isTypedData_Data()  {}
func (*TypedData_Http) isTypedData_Data()    {}
func (*TypedData_Int) isTypedData_Data()     {}
func (*TypedData_Double) isTypedData_Data()  {}

func (m *TypedData) GetData() isTypedData_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *TypedData) GetString_() string {
	if x, ok := m.GetData().(*TypedData_String_); ok {
		return x.String_
	}
	return ""
}

func (m *TypedData) GetJson() string {
	if x, ok := m.GetData().(*TypedData_Json); ok {
		return x.Json
	}
	return ""
}

func (m *TypedData) GetBytes() []byte {
	if x, ok := m.GetData().(*TypedData_Bytes); ok {
		return x.Bytes
	}
	return nil
}

func (m *TypedData) GetStream() []byte {
	if x, ok := m.GetData().(*TypedData_Stream); ok {
		return x.Stream
	}
	return nil
}

func (m *TypedData) GetHttp() *RpcHttp {
	if x, ok := m.GetData().(*TypedData_Http); ok {
		return x.Http
	}
	return nil
}

func (m *TypedData) GetInt() int64 {
	if x, ok := m.GetData().(*TypedData_Int); ok {
		return x.Int
	}
	return 0
}

func (m *TypedData) GetDouble() float64 {
	if x, ok := m.GetData().(*TypedData_Double); ok {
		return x.Double
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*TypedData) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _TypedData_OneofMarshaler, _TypedData_OneofUnmarshaler, _TypedData_OneofSizer, []interface{}{
		(*TypedData_String_)(nil),
		(*TypedData_Json)(nil),
		(*TypedData_Bytes)(nil),
		(*TypedData_Stream)(nil),
		(*TypedData_Http)(nil),
		(*TypedData_Int)(nil),
		(*TypedData_Double)(nil),
	}
}

func _TypedData_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*TypedData)
	// data
	switch x := m.Data.(type) {
	case *TypedData_String_:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.String_)
	case *TypedData_Json:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Json)
	case *TypedData_Bytes:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.Bytes)
	case *TypedData_Stream:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.Stream)
	case *TypedData_Http:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Http); err != nil {
			return err
		}
	case *TypedData_Int:
		b.EncodeVarint(6<<3 | proto.WireVarint)
		b.EncodeZigzag64(uint64(x.Int))
	case *TypedData_Double:
		b.EncodeVarint(7<<3 | proto.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.Double))
	case nil:
	default:
		return fmt.Errorf("TypedData.Data has unexpected type %T", x)
	}
	return nil
}

func _TypedData_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*TypedData)
	switch tag {
	case 1: // data.string
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Data = &TypedData_String_{x}
		return true, err
	case 2: // data.json
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Data = &TypedData_Json{x}
		return true, err
	case 3: // data.bytes
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Data = &TypedData_Bytes{x}
		return true, err
	case 4: // data.stream
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Data = &TypedData_Stream{x}
		return true, err
	case 5: // data.http
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RpcHttp)
		err := b.DecodeMessage(msg)
		m.Data = &TypedData_Http{msg}
		return true, err
	case 6: // data.int
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeZigzag64()
		m.Data = &TypedData_Int{int64(x)}
		return true, err
	case 7: // data.double
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Data = &TypedData_Double{math.Float64frombits(x)}
		return true, err
	default:
		return false, nil
	}
}

func _TypedData_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*TypedData)
	// data
	switch x := m.Data.(type) {
	case *TypedData_String_:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.String_)))
		n += len(x.String_)
	case *TypedData_Json:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Json)))
		n += len(x.Json)
	case *TypedData_Bytes:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Bytes)))
		n += len(x.Bytes)
	case *TypedData_Stream:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Stream)))
		n += len(x.Stream)
	case *TypedData_Http:
		s := proto.Size(x.Http)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *TypedData_Int:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(uint64(x.Int<<1) ^ uint64((int64(x.Int) >> 63))))
	case *TypedData_Double:
		n += 1 // tag and wire
		n += 8
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// Used to describe a given binding on invocation
type ParameterBinding struct {
	// Name for the binding
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Data for the binding
	Data                 *TypedData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ParameterBinding) Reset()         { *m = ParameterBinding{} }
func (m *ParameterBinding) String() string { return proto.CompactTextString(m) }
func (*ParameterBinding) ProtoMessage()    {}
func (*ParameterBinding) Descriptor() ([]byte, []int) {
	return fileDescriptor_FunctionRpc_783c3044933d63dc, []int{18}
}
func (m *ParameterBinding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParameterBinding.Unmarshal(m, b)
}
func (m *ParameterBinding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParameterBinding.Marshal(b, m, deterministic)
}
func (dst *ParameterBinding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParameterBinding.Merge(dst, src)
}
func (m *ParameterBinding) XXX_Size() int {
	return xxx_messageInfo_ParameterBinding.Size(m)
}
func (m *ParameterBinding) XXX_DiscardUnknown() {
	xxx_messageInfo_ParameterBinding.DiscardUnknown(m)
}

var xxx_messageInfo_ParameterBinding proto.InternalMessageInfo

func (m *ParameterBinding) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ParameterBinding) GetData() *TypedData {
	if m != nil {
		return m.Data
	}
	return nil
}

// Used to describe a given binding on load
type BindingInfo struct {
	// Type of binding (e.g. HttpTrigger)
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Direction of the given binding
	Direction            BindingInfo_Direction `protobuf:"varint,3,opt,name=direction,proto3,enum=AzureFunctionsRpcMessages.BindingInfo_Direction" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *BindingInfo) Reset()         { *m = BindingInfo{} }
func (m *BindingInfo) String() string { return proto.CompactTextString(m) }
func (*BindingInfo) ProtoMessage()    {}
func (*BindingInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_FunctionRpc_783c3044933d63dc, []int{19}
}
func (m *BindingInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindingInfo.Unmarshal(m, b)
}
func (m *BindingInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindingInfo.Marshal(b, m, deterministic)
}
func (dst *BindingInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindingInfo.Merge(dst, src)
}
func (m *BindingInfo) XXX_Size() int {
	return xxx_messageInfo_BindingInfo.Size(m)
}
func (m *BindingInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BindingInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BindingInfo proto.InternalMessageInfo

func (m *BindingInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *BindingInfo) GetDirection() BindingInfo_Direction {
	if m != nil {
		return m.Direction
	}
	return BindingInfo_in
}

// Used to send logs back to the Host
type RpcLog struct {
	// Unique id for invocation (if exists)
	InvocationId string `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	// TOD: This should be an enum
	// Category for the log (startup, load, invocation, etc.)
	Category string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	// Level for the given log message
	Level RpcLog_Level `protobuf:"varint,3,opt,name=level,proto3,enum=AzureFunctionsRpcMessages.RpcLog_Level" json:"level,omitempty"`
	// Message for the given log
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// Id for the even associated with this log (if exists)
	EventId string `protobuf:"bytes,5,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Exception (if exists)
	Exception *RpcException `protobuf:"bytes,6,opt,name=exception,proto3" json:"exception,omitempty"`
	// json serialized property bag, or could use a type scheme like map<string, TypedData>
	Properties           string   `protobuf:"bytes,7,opt,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcLog) Reset()         { *m = RpcLog{} }
func (m *RpcLog) String() string { return proto.CompactTextString(m) }
func (*RpcLog) ProtoMessage()    {}
func (*RpcLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_FunctionRpc_783c3044933d63dc, []int{20}
}
func (m *RpcLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcLog.Unmarshal(m, b)
}
func (m *RpcLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcLog.Marshal(b, m, deterministic)
}
func (dst *RpcLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcLog.Merge(dst, src)
}
func (m *RpcLog) XXX_Size() int {
	return xxx_messageInfo_RpcLog.Size(m)
}
func (m *RpcLog) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcLog.DiscardUnknown(m)
}

var xxx_messageInfo_RpcLog proto.InternalMessageInfo

func (m *RpcLog) GetInvocationId() string {
	if m != nil {
		return m.InvocationId
	}
	return ""
}

func (m *RpcLog) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *RpcLog) GetLevel() RpcLog_Level {
	if m != nil {
		return m.Level
	}
	return RpcLog_Trace
}

func (m *RpcLog) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RpcLog) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *RpcLog) GetException() *RpcException {
	if m != nil {
		return m.Exception
	}
	return nil
}

func (m *RpcLog) GetProperties() string {
	if m != nil {
		return m.Properties
	}
	return ""
}

// Encapsulates an Exception
type RpcException struct {
	// Source of the exception
	Source string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// Stack trace for the exception
	StackTrace string `protobuf:"bytes,1,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	// Textual message describing hte exception
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcException) Reset()         { *m = RpcException{} }
func (m *RpcException) String() string { return proto.CompactTextString(m) }
func (*RpcException) ProtoMessage()    {}
func (*RpcException) Descriptor() ([]byte, []int) {
	return fileDescriptor_FunctionRpc_783c3044933d63dc, []int{21}
}
func (m *RpcException) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcException.Unmarshal(m, b)
}
func (m *RpcException) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcException.Marshal(b, m, deterministic)
}
func (dst *RpcException) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcException.Merge(dst, src)
}
func (m *RpcException) XXX_Size() int {
	return xxx_messageInfo_RpcException.Size(m)
}
func (m *RpcException) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcException.DiscardUnknown(m)
}

var xxx_messageInfo_RpcException proto.InternalMessageInfo

func (m *RpcException) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *RpcException) GetStackTrace() string {
	if m != nil {
		return m.StackTrace
	}
	return ""
}

func (m *RpcException) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// TODO - solidify this or remove it
type RpcHttp struct {
	Method                   string            `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url                      string            `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Headers                  map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                     *TypedData        `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Params                   map[string]string `protobuf:"bytes,10,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StatusCode               string            `protobuf:"bytes,12,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Query                    map[string]string `protobuf:"bytes,15,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	EnableContentNegotiation bool              `protobuf:"varint,16,opt,name=enable_content_negotiation,json=enableContentNegotiation,proto3" json:"enable_content_negotiation,omitempty"`
	RawBody                  *TypedData        `protobuf:"bytes,17,opt,name=rawBody,proto3" json:"rawBody,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}          `json:"-"`
	XXX_unrecognized         []byte            `json:"-"`
	XXX_sizecache            int32             `json:"-"`
}

func (m *RpcHttp) Reset()         { *m = RpcHttp{} }
func (m *RpcHttp) String() string { return proto.CompactTextString(m) }
func (*RpcHttp) ProtoMessage()    {}
func (*RpcHttp) Descriptor() ([]byte, []int) {
	return fileDescriptor_FunctionRpc_783c3044933d63dc, []int{22}
}
func (m *RpcHttp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcHttp.Unmarshal(m, b)
}
func (m *RpcHttp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcHttp.Marshal(b, m, deterministic)
}
func (dst *RpcHttp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcHttp.Merge(dst, src)
}
func (m *RpcHttp) XXX_Size() int {
	return xxx_messageInfo_RpcHttp.Size(m)
}
func (m *RpcHttp) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcHttp.DiscardUnknown(m)
}

var xxx_messageInfo_RpcHttp proto.InternalMessageInfo

func (m *RpcHttp) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *RpcHttp) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *RpcHttp) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *RpcHttp) GetBody() *TypedData {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *RpcHttp) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *RpcHttp) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *RpcHttp) GetQuery() map[string]string {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *RpcHttp) GetEnableContentNegotiation() bool {
	if m != nil {
		return m.EnableContentNegotiation
	}
	return false
}

func (m *RpcHttp) GetRawBody() *TypedData {
	if m != nil {
		return m.RawBody
	}
	return nil
}

func init() {
	proto.RegisterType((*StreamingMessage)(nil), "AzureFunctionsRpcMessages.StreamingMessage")
	proto.RegisterType((*StartStream)(nil), "AzureFunctionsRpcMessages.StartStream")
	proto.RegisterType((*WorkerInitRequest)(nil), "AzureFunctionsRpcMessages.WorkerInitRequest")
	proto.RegisterMapType((map[string]string)(nil), "AzureFunctionsRpcMessages.WorkerInitRequest.CapabilitiesEntry")
	proto.RegisterMapType((map[string]RpcLog_Level)(nil), "AzureFunctionsRpcMessages.WorkerInitRequest.LogCategoriesEntry")
	proto.RegisterType((*WorkerInitResponse)(nil), "AzureFunctionsRpcMessages.WorkerInitResponse")
	proto.RegisterMapType((map[string]string)(nil), "AzureFunctionsRpcMessages.WorkerInitResponse.CapabilitiesEntry")
	proto.RegisterType((*StatusResult)(nil), "AzureFunctionsRpcMessages.StatusResult")
	proto.RegisterType((*WorkerHeartbeat)(nil), "AzureFunctionsRpcMessages.WorkerHeartbeat")
	proto.RegisterType((*WorkerTerminate)(nil), "AzureFunctionsRpcMessages.WorkerTerminate")
	proto.RegisterType((*FileChangeEventRequest)(nil), "AzureFunctionsRpcMessages.FileChangeEventRequest")
	proto.RegisterType((*WorkerActionResponse)(nil), "AzureFunctionsRpcMessages.WorkerActionResponse")
	proto.RegisterType((*WorkerStatusRequest)(nil), "AzureFunctionsRpcMessages.WorkerStatusRequest")
	proto.RegisterType((*WorkerStatusResponse)(nil), "AzureFunctionsRpcMessages.WorkerStatusResponse")
	proto.RegisterType((*FunctionLoadRequest)(nil), "AzureFunctionsRpcMessages.FunctionLoadRequest")
	proto.RegisterType((*FunctionLoadResponse)(nil), "AzureFunctionsRpcMessages.FunctionLoadResponse")
	proto.RegisterType((*RpcFunctionMetadata)(nil), "AzureFunctionsRpcMessages.RpcFunctionMetadata")
	proto.RegisterMapType((map[string]*BindingInfo)(nil), "AzureFunctionsRpcMessages.RpcFunctionMetadata.BindingsEntry")
	proto.RegisterType((*InvocationRequest)(nil), "AzureFunctionsRpcMessages.InvocationRequest")
	proto.RegisterMapType((map[string]*TypedData)(nil), "AzureFunctionsRpcMessages.InvocationRequest.TriggerMetadataEntry")
	proto.RegisterType((*InvocationCancel)(nil), "AzureFunctionsRpcMessages.InvocationCancel")
	proto.RegisterType((*InvocationResponse)(nil), "AzureFunctionsRpcMessages.InvocationResponse")
	proto.RegisterType((*TypedData)(nil), "AzureFunctionsRpcMessages.TypedData")
	proto.RegisterType((*ParameterBinding)(nil), "AzureFunctionsRpcMessages.ParameterBinding")
	proto.RegisterType((*BindingInfo)(nil), "AzureFunctionsRpcMessages.BindingInfo")
	proto.RegisterType((*RpcLog)(nil), "AzureFunctionsRpcMessages.RpcLog")
	proto.RegisterType((*RpcException)(nil), "AzureFunctionsRpcMessages.RpcException")
	proto.RegisterType((*RpcHttp)(nil), "AzureFunctionsRpcMessages.RpcHttp")
	proto.RegisterMapType((map[string]string)(nil), "AzureFunctionsRpcMessages.RpcHttp.HeadersEntry")
	proto.RegisterMapType((map[string]string)(nil), "AzureFunctionsRpcMessages.RpcHttp.ParamsEntry")
	proto.RegisterMapType((map[string]string)(nil), "AzureFunctionsRpcMessages.RpcHttp.QueryEntry")
	proto.RegisterEnum("AzureFunctionsRpcMessages.StatusResult_Status", StatusResult_Status_name, StatusResult_Status_value)
	proto.RegisterEnum("AzureFunctionsRpcMessages.FileChangeEventRequest_Type", FileChangeEventRequest_Type_name, FileChangeEventRequest_Type_value)
	proto.RegisterEnum("AzureFunctionsRpcMessages.WorkerActionResponse_Action", WorkerActionResponse_Action_name, WorkerActionResponse_Action_value)
	proto.RegisterEnum("AzureFunctionsRpcMessages.BindingInfo_Direction", BindingInfo_Direction_name, BindingInfo_Direction_value)
	proto.RegisterEnum("AzureFunctionsRpcMessages.RpcLog_Level", RpcLog_Level_name, RpcLog_Level_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FunctionRpcClient is the client API for FunctionRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FunctionRpcClient interface {
	EventStream(ctx context.Context, opts ...grpc.CallOption) (FunctionRpc_EventStreamClient, error)
}

type functionRpcClient struct {
	cc *grpc.ClientConn
}

func NewFunctionRpcClient(cc *grpc.ClientConn) FunctionRpcClient {
	return &functionRpcClient{cc}
}

func (c *functionRpcClient) EventStream(ctx context.Context, opts ...grpc.CallOption) (FunctionRpc_EventStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FunctionRpc_serviceDesc.Streams[0], "/AzureFunctionsRpcMessages.FunctionRpc/EventStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &functionRpcEventStreamClient{stream}
	return x, nil
}

type FunctionRpc_EventStreamClient interface {
	Send(*StreamingMessage) error
	Recv() (*StreamingMessage, error)
	grpc.ClientStream
}

type functionRpcEventStreamClient struct {
	grpc.ClientStream
}

func (x *functionRpcEventStreamClient) Send(m *StreamingMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *functionRpcEventStreamClient) Recv() (*StreamingMessage, error) {
	m := new(StreamingMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FunctionRpcServer is the server API for FunctionRpc service.
type FunctionRpcServer interface {
	EventStream(FunctionRpc_EventStreamServer) error
}

func RegisterFunctionRpcServer(s *grpc.Server, srv FunctionRpcServer) {
	s.RegisterService(&_FunctionRpc_serviceDesc, srv)
}

func _FunctionRpc_EventStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FunctionRpcServer).EventStream(&functionRpcEventStreamServer{stream})
}

type FunctionRpc_EventStreamServer interface {
	Send(*StreamingMessage) error
	Recv() (*StreamingMessage, error)
	grpc.ServerStream
}

type functionRpcEventStreamServer struct {
	grpc.ServerStream
}

func (x *functionRpcEventStreamServer) Send(m *StreamingMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *functionRpcEventStreamServer) Recv() (*StreamingMessage, error) {
	m := new(StreamingMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _FunctionRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "AzureFunctionsRpcMessages.FunctionRpc",
	HandlerType: (*FunctionRpcServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EventStream",
			Handler:       _FunctionRpc_EventStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "FunctionRpc.proto",
}

func init() { proto.RegisterFile("FunctionRpc.proto", fileDescriptor_FunctionRpc_783c3044933d63dc) }

var fileDescriptor_FunctionRpc_783c3044933d63dc = []byte{
	// 2045 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x59, 0x4b, 0x73, 0xdb, 0xc8,
	0x11, 0x26, 0x48, 0x8a, 0x8f, 0x26, 0x25, 0x41, 0x63, 0x59, 0x45, 0x2b, 0xc9, 0xc6, 0x46, 0x1e,
	0x76, 0x79, 0x77, 0xe1, 0x5d, 0xa5, 0x92, 0x72, 0x5c, 0xce, 0xba, 0xac, 0x87, 0x97, 0x72, 0x64,
	0x47, 0x81, 0x9c, 0x75, 0x6a, 0xab, 0xb2, 0xd8, 0x21, 0x30, 0x84, 0x10, 0x83, 0x18, 0x78, 0x30,
	0x90, 0x56, 0xa9, 0x9c, 0x52, 0xf9, 0x03, 0x39, 0xe4, 0x92, 0x4b, 0x2a, 0x39, 0xe6, 0x90, 0xdf,
	0x91, 0x63, 0xfe, 0x40, 0xce, 0xf9, 0x15, 0xa9, 0x4a, 0xcd, 0x03, 0x20, 0x28, 0x72, 0xf9, 0x58,
	0xdf, 0xd0, 0xcd, 0xe9, 0xaf, 0x7b, 0xba, 0x7b, 0x7a, 0x3e, 0x80, 0xb0, 0xf5, 0x2c, 0x8b, 0x3d,
	0x1e, 0xd2, 0xd8, 0x49, 0x3c, 0x3b, 0x61, 0x94, 0x53, 0x74, 0xeb, 0xe9, 0xef, 0x32, 0x46, 0x72,
	0x7d, 0xea, 0x24, 0xde, 0x0b, 0x92, 0xa6, 0x38, 0x20, 0xe9, 0xee, 0x7b, 0x01, 0xa5, 0x41, 0x44,
	0x1e, 0xc8, 0x85, 0x83, 0x6c, 0xf8, 0xc0, 0xcf, 0x18, 0x16, 0xab, 0x94, 0xa9, 0xf5, 0xef, 0x0e,
	0x98, 0x67, 0x9c, 0x11, 0x3c, 0x0a, 0xe3, 0x40, 0x5b, 0xa1, 0xef, 0x00, 0x30, 0xf2, 0x36, 0x23,
	0x29, 0x77, 0x43, 0xbf, 0x67, 0xdc, 0x36, 0xee, 0xb5, 0x9d, 0xb6, 0xd6, 0x1c, 0xfb, 0xe8, 0xe7,
	0xd0, 0x4d, 0x39, 0x66, 0xdc, 0x4d, 0xa5, 0x61, 0x6f, 0xfb, 0xb6, 0x71, 0xaf, 0xb3, 0xf7, 0x43,
	0xfb, 0x6b, 0xa3, 0xb0, 0xcf, 0xc4, 0x72, 0xe5, 0xa6, 0x5f, 0x71, 0x3a, 0xe9, 0x58, 0x44, 0x5f,
	0xc0, 0x8d, 0x4b, 0xca, 0xde, 0x10, 0xe6, 0x86, 0x71, 0xc8, 0x5d, 0xed, 0xa5, 0xb7, 0x25, 0x31,
	0x3f, 0x98, 0x83, 0xf9, 0x5a, 0x5a, 0x1d, 0xc7, 0x21, 0x77, 0x94, 0x4d, 0xbf, 0xe2, 0x6c, 0x5d,
	0x5e, 0x57, 0x22, 0x0c, 0xdb, 0x93, 0xf8, 0x69, 0x42, 0xe3, 0x94, 0xf4, 0x4c, 0xe9, 0xe0, 0xc3,
	0x25, 0x1d, 0x28, 0xa3, 0x7e, 0xc5, 0x41, 0x97, 0x53, 0x5a, 0xf4, 0x1a, 0x4c, 0xed, 0xe2, 0x9c,
	0x60, 0xc6, 0x07, 0x04, 0xf3, 0xde, 0xa6, 0x84, 0xbf, 0xbf, 0x10, 0xbe, 0x9f, 0x5b, 0xf4, 0x2b,
	0xce, 0xe6, 0xe5, 0xa4, 0xaa, 0x04, 0xcc, 0x09, 0x1b, 0x85, 0x31, 0xe6, 0xa4, 0xb7, 0xb1, 0x24,
	0xf0, 0xab, 0xdc, 0x62, 0x0c, 0x5c, 0xa8, 0x90, 0x0f, 0x37, 0x35, 0x70, 0xca, 0x31, 0xcf, 0xd2,
	0x22, 0xed, 0x5d, 0x89, 0x6e, 0x2f, 0x44, 0x3f, 0x93, 0x66, 0xe3, 0xc4, 0xeb, 0x1a, 0x4e, 0xa8,
	0x51, 0x00, 0x3b, 0xd7, 0xbd, 0xe8, 0xe4, 0xaf, 0x4b, 0x37, 0x0f, 0x96, 0x76, 0x53, 0xa4, 0x7f,
	0xfb, 0x72, 0x86, 0x1e, 0xc5, 0x70, 0x6b, 0x18, 0x46, 0xc4, 0xf5, 0xce, 0x71, 0x1c, 0x10, 0x97,
	0x5c, 0x90, 0x78, 0xdc, 0x49, 0x0d, 0xe9, 0xeb, 0xe3, 0x39, 0xbe, 0x9e, 0x85, 0x11, 0x39, 0x90,
	0xa6, 0x47, 0xc2, 0x72, 0xbc, 0xab, 0x9d, 0xe1, 0xcc, 0x5f, 0x4a, 0x1b, 0xc3, 0x12, 0x6d, 0xbc,
	0xb1, 0xe6, 0x92, 0x1b, 0x7b, 0xaa, 0x4e, 0xf0, 0xd4, 0xc6, 0x26, 0xf5, 0xa2, 0x4e, 0x43, 0x0d,
	0xe2, 0x46, 0x14, 0xfb, 0xc5, 0xa6, 0x5a, 0x0b, 0xeb, 0x94, 0x2b, 0x4f, 0x28, 0xf6, 0x4b, 0x75,
	0x1a, 0x4e, 0xab, 0xc5, 0x76, 0xae, 0x7b, 0xd1, 0xdb, 0x69, 0x2f, 0xdc, 0xce, 0xa4, 0x9b, 0xf1,
	0x76, 0x86, 0x33, 0xf4, 0xe8, 0x37, 0x80, 0xc2, 0xf8, 0x82, 0x7a, 0x58, 0x27, 0x4d, 0xed, 0xa5,
	0xbe, 0xf0, 0xa8, 0x1f, 0x17, 0x46, 0xa5, 0xa3, 0x1e, 0x5e, 0x57, 0xa2, 0x2f, 0xe1, 0xc6, 0x04,
	0xbc, 0xde, 0xc4, 0xda, 0xc2, 0x93, 0x5e, 0xc6, 0x1f, 0x9f, 0xf4, 0x70, 0x4a, 0x8b, 0x3e, 0x87,
	0x92, 0x5b, 0xd7, 0xc3, 0xb1, 0x47, 0xa2, 0xde, 0x4d, 0x89, 0xff, 0xfe, 0x52, 0xf8, 0x07, 0xd2,
	0xa4, 0x5f, 0x71, 0xcc, 0xf0, 0x9a, 0x0e, 0x3d, 0x86, 0x26, 0x4b, 0x3c, 0x37, 0xa2, 0x41, 0xaf,
	0x2a, 0x11, 0xef, 0xcc, 0x41, 0x74, 0x12, 0xef, 0x84, 0x06, 0xfd, 0x8a, 0xd3, 0x60, 0xf2, 0x69,
	0xbf, 0x0d, 0x4d, 0x8f, 0xc6, 0x9c, 0xc4, 0xdc, 0xba, 0x0f, 0x9d, 0xd2, 0xbc, 0x45, 0xdf, 0x82,
	0x76, 0x3e, 0x00, 0x7d, 0x89, 0xdc, 0x76, 0x5a, 0x7a, 0x88, 0xf9, 0xd6, 0x3f, 0x6b, 0xb0, 0x35,
	0x35, 0x48, 0xd1, 0x1d, 0xe8, 0x9e, 0xd3, 0x94, 0xbb, 0x17, 0x84, 0xa5, 0x21, 0x8d, 0xf5, 0x0d,
	0xd0, 0x11, 0xba, 0xcf, 0x94, 0x0a, 0x0d, 0xa0, 0xeb, 0xe1, 0x04, 0x0f, 0xc2, 0x28, 0xe4, 0x21,
	0x49, 0x7b, 0xd5, 0xdb, 0xb5, 0x7b, 0x9d, 0xbd, 0x4f, 0x56, 0x99, 0xd7, 0xf6, 0x41, 0x09, 0xe0,
	0x28, 0xe6, 0xec, 0xca, 0x99, 0xc0, 0x44, 0x43, 0xd8, 0x88, 0x68, 0xe0, 0x7a, 0x98, 0x93, 0x80,
	0x32, 0xe1, 0xa5, 0x26, 0xbd, 0x3c, 0x59, 0xc9, 0xcb, 0x09, 0x0d, 0x0e, 0x0a, 0x04, 0xe5, 0x66,
	0x3d, 0x2a, 0xeb, 0x76, 0x9f, 0xc0, 0xd6, 0x54, 0x28, 0xc8, 0x84, 0xda, 0x1b, 0x72, 0xa5, 0xb7,
	0x2e, 0x1e, 0xd1, 0x36, 0xac, 0x5d, 0xe0, 0x28, 0x23, 0x3a, 0x89, 0x4a, 0x78, 0x54, 0x7d, 0x68,
	0xec, 0x86, 0x80, 0xa6, 0xbd, 0xcc, 0x40, 0xf8, 0x59, 0x19, 0x61, 0x63, 0xef, 0xee, 0xc2, 0x02,
	0xdb, 0x27, 0xe4, 0x82, 0x44, 0x25, 0x57, 0xd6, 0xdf, 0xab, 0x80, 0xa6, 0x2f, 0x26, 0xf4, 0x03,
	0xd8, 0xd0, 0x45, 0x9e, 0xac, 0xd9, 0xba, 0xd2, 0xe6, 0x55, 0xf3, 0x66, 0x56, 0xed, 0xc9, 0x4a,
	0x97, 0xe0, 0xc2, 0xb2, 0x3d, 0x81, 0x06, 0x23, 0x69, 0x16, 0xf1, 0x5e, 0x4d, 0xf6, 0xf1, 0xdd,
	0xf9, 0xc4, 0x40, 0x0d, 0xf2, 0x2c, 0xe2, 0x8e, 0x36, 0x7b, 0xe7, 0x7a, 0x58, 0x7f, 0xad, 0x42,
	0xb7, 0x8c, 0x8c, 0x9e, 0x41, 0x43, 0x5d, 0x41, 0x72, 0xd8, 0x6c, 0xcc, 0x1d, 0x9c, 0x65, 0xc3,
	0x5c, 0xd0, 0xd6, 0x68, 0xa7, 0xd8, 0x9a, 0x8a, 0x43, 0x4b, 0xe8, 0x08, 0xda, 0xe4, 0x2b, 0x8f,
	0x24, 0x02, 0x4c, 0x9f, 0xde, 0x05, 0xc5, 0x3d, 0xca, 0x97, 0x3b, 0x63, 0x4b, 0xf4, 0x63, 0xa8,
	0x47, 0x34, 0xc8, 0xdb, 0x7c, 0xf1, 0xf9, 0x77, 0xe4, 0x72, 0xeb, 0x63, 0x68, 0xa8, 0x38, 0x51,
	0x07, 0x9a, 0xcf, 0x70, 0x18, 0x65, 0x8c, 0x98, 0x15, 0x21, 0x9c, 0x65, 0x9e, 0x47, 0xd2, 0xd4,
	0x34, 0xd0, 0x3a, 0xb4, 0xd5, 0x9c, 0x89, 0x88, 0x6f, 0x56, 0xad, 0x2d, 0xd8, 0xbc, 0xc6, 0x3f,
	0xac, 0x5f, 0xe4, 0xaa, 0x31, 0x4d, 0x78, 0x0c, 0xdd, 0x80, 0x61, 0x8f, 0xb8, 0x09, 0x61, 0x21,
	0x55, 0x4c, 0xb0, 0xb3, 0x77, 0xcb, 0x56, 0x9c, 0xd2, 0xce, 0x39, 0xa5, 0x7d, 0xa8, 0x39, 0xa5,
	0xd3, 0x91, 0xcb, 0x4f, 0xe5, 0x6a, 0xeb, 0xbf, 0x06, 0xec, 0xcc, 0xbe, 0x5a, 0xd1, 0x73, 0xa8,
	0xf3, 0xab, 0x84, 0x48, 0xc0, 0x8d, 0xbd, 0x9f, 0xac, 0x7c, 0x37, 0xdb, 0xaf, 0xae, 0x12, 0xe2,
	0x48, 0x0c, 0x31, 0xdf, 0x86, 0x59, 0x14, 0xb9, 0x09, 0xe6, 0xe7, 0xf9, 0x7c, 0x13, 0x8a, 0x53,
	0xcc, 0xcf, 0x11, 0x82, 0x7a, 0x8c, 0x47, 0x44, 0x76, 0x62, 0xdb, 0x91, 0xcf, 0xd6, 0x29, 0xd4,
	0x85, 0xb9, 0xc8, 0xcf, 0xaf, 0xe2, 0x37, 0x31, 0xbd, 0x8c, 0x55, 0xb2, 0x0e, 0x18, 0xc1, 0x9c,
	0xf8, 0xa6, 0x21, 0x84, 0x43, 0x12, 0x11, 0x21, 0x54, 0xe5, 0x2f, 0x32, 0x00, 0xdf, 0xac, 0x0b,
	0xc1, 0x21, 0x02, 0xc5, 0x37, 0x5b, 0xa8, 0x09, 0xb5, 0xa7, 0x51, 0x64, 0x6e, 0x5a, 0x7f, 0x33,
	0x60, 0x7b, 0xd6, 0xbd, 0x8e, 0x5e, 0x42, 0x43, 0x31, 0x84, 0x25, 0x76, 0x3a, 0x0b, 0xc0, 0xd6,
	0xa2, 0x46, 0x51, 0xfd, 0x87, 0x53, 0xdd, 0x64, 0xb2, 0xff, 0x84, 0x64, 0xdd, 0x81, 0x86, 0x5a,
	0xa9, 0x02, 0x94, 0xfc, 0xda, 0xac, 0x20, 0x80, 0x86, 0x43, 0xc4, 0x8d, 0x6e, 0x1a, 0xd6, 0x4d,
	0xb8, 0x31, 0x83, 0xba, 0x59, 0x3b, 0x79, 0xe4, 0x93, 0x94, 0xca, 0xfa, 0x83, 0x01, 0x37, 0x66,
	0x50, 0x08, 0xf4, 0x5d, 0xe8, 0x14, 0x5c, 0xa1, 0x78, 0x37, 0x80, 0x5c, 0x75, 0xec, 0xa3, 0xe7,
	0xd0, 0x1a, 0x11, 0x8e, 0x7d, 0xcc, 0xb1, 0x3e, 0x09, 0xf6, 0xfc, 0x3e, 0xce, 0xf5, 0x2f, 0xb4,
	0x95, 0x53, 0xd8, 0x5b, 0x5f, 0xc1, 0xf6, 0x2c, 0x7e, 0xb1, 0x38, 0x88, 0xf1, 0x08, 0xaa, 0x7e,
	0xa3, 0x11, 0x64, 0xfd, 0xab, 0x0a, 0x37, 0x66, 0xc4, 0x56, 0xf4, 0x53, 0x7d, 0xdc, 0x4f, 0xe8,
	0xdb, 0xd0, 0xf6, 0x43, 0x46, 0x3c, 0x4e, 0x59, 0x3e, 0x9f, 0xc6, 0x0a, 0x11, 0x6b, 0xea, 0xb1,
	0x30, 0xe1, 0xae, 0x20, 0x93, 0xba, 0x6e, 0xa0, 0x54, 0xa2, 0xb9, 0xc5, 0x02, 0x22, 0x26, 0x9c,
	0x9b, 0xd0, 0x30, 0xe6, 0xba, 0x53, 0x41, 0xaa, 0x4e, 0x85, 0x06, 0xfd, 0x1a, 0x5a, 0x83, 0x30,
	0xf6, 0xc3, 0x38, 0x48, 0x7b, 0x0d, 0x39, 0x19, 0x1e, 0xaf, 0x96, 0x51, 0x7b, 0x5f, 0x9b, 0xab,
	0x69, 0x5d, 0xa0, 0xed, 0x7a, 0xb0, 0x3e, 0xf1, 0xd3, 0x8c, 0x21, 0xfb, 0xb8, 0x3c, 0x64, 0xe7,
	0xbf, 0xe4, 0x69, 0xa8, 0xe3, 0x78, 0x48, 0xcb, 0xc3, 0xf8, 0x7f, 0x55, 0xd8, 0x9a, 0x22, 0x70,
	0xe8, 0x7b, 0xb0, 0x5e, 0x62, 0x52, 0x45, 0x11, 0xbb, 0x63, 0xe5, 0xb1, 0x7f, 0xbd, 0xce, 0xd5,
	0x19, 0xcd, 0x06, 0x61, 0x9c, 0x64, 0xdc, 0x95, 0xed, 0xa6, 0xc6, 0xe6, 0x3c, 0x22, 0x76, 0x8a,
	0x19, 0x1e, 0x11, 0x4e, 0x98, 0x8e, 0xd5, 0x69, 0x4b, 0xf3, 0x43, 0x51, 0xda, 0x08, 0x4c, 0xce,
	0xc2, 0x20, 0x20, 0xcc, 0x2d, 0x1a, 0xb8, 0x2e, 0x11, 0x9f, 0xae, 0x42, 0x4d, 0xed, 0x57, 0x0a,
	0x24, 0x4f, 0xbe, 0xca, 0xf9, 0x26, 0x9f, 0xd4, 0xee, 0x9e, 0xc3, 0xf6, 0xac, 0x85, 0x33, 0x2a,
	0xf0, 0x68, 0xb2, 0x02, 0xdf, 0x9f, 0x13, 0x8c, 0x18, 0x6b, 0xbe, 0xd8, 0x4c, 0x39, 0xff, 0x19,
	0x98, 0xd7, 0xf9, 0xe7, 0x74, 0xf6, 0xab, 0x33, 0xb2, 0xff, 0x6e, 0xd3, 0xff, 0x4f, 0x55, 0x40,
	0xd3, 0xbc, 0x7a, 0xb9, 0xba, 0x9f, 0x40, 0x87, 0x66, 0xbc, 0xa8, 0x6b, 0x75, 0xf5, 0xba, 0x82,
	0xb2, 0x97, 0x85, 0xfd, 0x14, 0xba, 0x8c, 0xf0, 0x8c, 0xc5, 0xae, 0xca, 0x63, 0x7d, 0x85, 0x3c,
	0x76, 0x94, 0xe5, 0x67, 0xc2, 0xf0, 0x9d, 0x89, 0x8d, 0xf5, 0x1f, 0x03, 0xda, 0x05, 0x36, 0xea,
	0x09, 0x52, 0xc2, 0xc2, 0x38, 0x50, 0x39, 0x10, 0x64, 0x5e, 0xc9, 0x68, 0x1b, 0xea, 0xbf, 0x2d,
	0x86, 0x7c, 0xbf, 0xe2, 0x48, 0x09, 0xed, 0xc0, 0xda, 0xe0, 0x8a, 0x4b, 0x16, 0x6c, 0xdc, 0xeb,
	0xf6, 0x2b, 0x8e, 0x12, 0x35, 0x0e, 0xc1, 0x23, 0xb9, 0xb3, 0xae, 0xc6, 0x11, 0xd4, 0xff, 0x21,
	0xd4, 0xcf, 0x39, 0x4f, 0xf4, 0x1b, 0x90, 0x35, 0x7f, 0x6a, 0xf4, 0x39, 0x4f, 0x84, 0x2f, 0x61,
	0x81, 0x10, 0xd4, 0xc4, 0x30, 0x12, 0xef, 0xce, 0xa8, 0x5f, 0x71, 0x84, 0x20, 0xfc, 0xf8, 0x34,
	0x1b, 0x44, 0xea, 0x2d, 0xd7, 0x10, 0x7e, 0x94, 0xbc, 0xdf, 0x80, 0xba, 0x9c, 0xd7, 0x5f, 0x82,
	0x79, 0xbd, 0x12, 0xc5, 0xc4, 0x34, 0x4a, 0x13, 0xf3, 0xa1, 0x5a, 0xbf, 0x52, 0x47, 0x2b, 0x0f,
	0x7f, 0x31, 0xa0, 0x53, 0x9a, 0x33, 0x02, 0x5d, 0x12, 0x09, 0xd5, 0xbf, 0x8a, 0x10, 0xbc, 0xcc,
	0xe7, 0xb1, 0xb8, 0x77, 0x6b, 0xf2, 0xde, 0xfd, 0x68, 0xb9, 0xb1, 0x65, 0x1f, 0xe6, 0x76, 0xce,
	0x18, 0xc2, 0xba, 0x0b, 0xed, 0x42, 0x8f, 0x1a, 0x50, 0x0d, 0x05, 0x5f, 0x68, 0x42, 0x8d, 0x66,
	0xdc, 0x34, 0x50, 0x1b, 0xd6, 0xc2, 0x58, 0x3c, 0x56, 0xad, 0x3f, 0xd6, 0xa0, 0xa1, 0x88, 0xd9,
	0x72, 0x6d, 0xbe, 0x0b, 0x2d, 0xfd, 0x6e, 0x73, 0x95, 0x13, 0x97, 0x5c, 0x16, 0xaf, 0x0a, 0x91,
	0xe0, 0xfe, 0x7a, 0x03, 0xcb, 0xbf, 0x2a, 0x48, 0x2b, 0xd4, 0x83, 0xe6, 0x48, 0xfd, 0xae, 0xaf,
	0xaa, 0x5c, 0x44, 0xb7, 0xa0, 0xa5, 0xbe, 0x8f, 0x84, 0xbe, 0xec, 0x8b, 0xb6, 0xd3, 0x94, 0xf2,
	0xb1, 0x3f, 0xc9, 0x62, 0x1b, 0xdf, 0x98, 0xc5, 0xbe, 0x07, 0x90, 0x30, 0x9a, 0x10, 0x26, 0x5f,
	0x31, 0x9a, 0x6a, 0x68, 0x8f, 0x35, 0xd6, 0x17, 0xb0, 0x26, 0x63, 0x15, 0xa9, 0x7b, 0x25, 0x26,
	0x86, 0x59, 0x11, 0x8f, 0x87, 0x64, 0x90, 0x05, 0xa6, 0x81, 0x36, 0xa1, 0x23, 0x6a, 0xc1, 0x46,
	0x32, 0x4d, 0x8a, 0x80, 0xbd, 0xc6, 0x2c, 0x0e, 0xe3, 0xc0, 0xac, 0x89, 0x85, 0x47, 0x8c, 0x51,
	0x66, 0xd6, 0x51, 0x17, 0x5a, 0x07, 0x2c, 0xe4, 0xa1, 0x87, 0x23, 0x73, 0x0d, 0xb5, 0xa0, 0xfe,
	0x92, 0xc6, 0xc4, 0x6c, 0x58, 0x18, 0xba, 0xe5, 0xd0, 0x04, 0x69, 0x4a, 0x69, 0xc6, 0xbc, 0x9c,
	0x05, 0x6a, 0x49, 0xde, 0xcc, 0x1c, 0x7b, 0x6f, 0x5c, 0x2e, 0x82, 0xc8, 0x59, 0x84, 0x54, 0xc9,
	0xb0, 0xca, 0x49, 0xac, 0x4e, 0x24, 0xd1, 0xfa, 0xf3, 0x1a, 0x34, 0xf5, 0x91, 0x11, 0xf0, 0x23,
	0xc2, 0xcf, 0x69, 0x5e, 0x63, 0x2d, 0x89, 0x49, 0x9e, 0xb1, 0x48, 0x5b, 0x8a, 0x47, 0x74, 0x0c,
	0xcd, 0x73, 0x82, 0x7d, 0xc2, 0x72, 0x86, 0xff, 0x60, 0xf1, 0x89, 0xb4, 0xfb, 0xca, 0x42, 0x5d,
	0x23, 0xb9, 0xbd, 0x38, 0x41, 0x03, 0xea, 0x5f, 0xad, 0x34, 0xcb, 0xa4, 0x85, 0x78, 0x15, 0x4a,
	0xc4, 0x19, 0x4d, 0x7b, 0x20, 0x63, 0xb0, 0x97, 0x88, 0x41, 0x1e, 0x6a, 0x1d, 0x82, 0xb6, 0xd6,
	0xd9, 0xe3, 0x59, 0xea, 0x7a, 0xd4, 0x27, 0xf2, 0xc3, 0xa1, 0xca, 0x1e, 0xcf, 0xd2, 0x03, 0xea,
	0x13, 0x74, 0x00, 0x6b, 0x6f, 0x33, 0xc2, 0xae, 0x7a, 0x9b, 0xd2, 0xcf, 0x87, 0x4b, 0xf8, 0xf9,
	0xa5, 0x58, 0xaf, 0xdc, 0x28, 0x5b, 0xf4, 0x18, 0x76, 0x49, 0x8c, 0x07, 0x11, 0x71, 0xf5, 0xd7,
	0x0d, 0x37, 0x26, 0x01, 0xe5, 0xa1, 0xec, 0x0d, 0xf9, 0x0d, 0xb7, 0xe5, 0xf4, 0xd4, 0x8a, 0x03,
	0xb5, 0xe0, 0xe5, 0xf8, 0x77, 0xf4, 0x09, 0x34, 0x19, 0xbe, 0xdc, 0x17, 0x89, 0xda, 0x5a, 0x21,
	0x51, 0xb9, 0xd1, 0xee, 0x23, 0xe8, 0x96, 0xd3, 0xbf, 0xd2, 0x37, 0x81, 0x9f, 0x42, 0xa7, 0x94,
	0xb6, 0x95, 0x4c, 0x1f, 0x02, 0x8c, 0x33, 0xb1, 0x8a, 0xe5, 0xde, 0xef, 0xa1, 0x53, 0xfa, 0x77,
	0x00, 0x8d, 0xa0, 0x23, 0xdf, 0x9a, 0xf4, 0x97, 0xa0, 0xf7, 0xe7, 0xde, 0x57, 0x93, 0xff, 0x01,
	0xec, 0xae, 0xb2, 0xd8, 0xaa, 0xdc, 0x33, 0x3e, 0x32, 0xf6, 0xdf, 0xc2, 0x7d, 0x8f, 0x8e, 0xec,
	0x51, 0xe8, 0x31, 0x9a, 0xd2, 0x21, 0xb7, 0xb1, 0x40, 0xb0, 0x73, 0xbe, 0x96, 0xda, 0x2c, 0xf1,
	0x6c, 0x7d, 0x84, 0xd2, 0xfd, 0xf5, 0x1c, 0xfa, 0x54, 0x10, 0x89, 0x53, 0xe3, 0xf3, 0x1a, 0x4b,
	0xbc, 0x7f, 0x54, 0x3f, 0x78, 0x51, 0x98, 0xcb, 0x00, 0xec, 0xd7, 0x64, 0xf0, 0x9c, 0x0e, 0x52,
	0xfb, 0x4c, 0x52, 0x66, 0xfb, 0x53, 0x01, 0x92, 0x47, 0x32, 0x68, 0x48, 0x16, 0xf2, 0xa3, 0xff,
	0x07, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xf5, 0x32, 0x05, 0x15, 0x19, 0x00, 0x00,
}
